on:
  pull_request:
  push:
    branches: [main]

name: thumbv8m-mpu CI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run tests
        run: cargo test --tests --target $(rustc --print=host-tuple)

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Add default build target
        run: rustup target add thumbv8m.main-none-eabihf
      - name: Build basic example
        run: cargo build --release --example basic --target thumbv8m.main-none-eabihf

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Add default build target
        run: rustup target add thumbv8m.main-none-eabihf
      - name: Run clippy
        run: cargo clippy -- -Dwarnings

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check formatting
        run: cargo fmt -- --check
